version: '3.7'
services:
  web:
    build:
      context: ./components/CodeRx/
      dockerfile: ./coderx.Dockerfile
    expose:
     - "5000"
    environment: 
      - FLASK_DEBUG=1
    volumes:
      - "./components/CodeRx:/code/CodeRx"

  redis:
    image: "redis:alpine"

  db:
    image: postgres:11.2-alpine
    restart: always
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: CodeRxYourDailyDoseOfCode
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  nginx:
    depends_on:
        - web
    image: nginx:alpine
    volumes:
      - ./components/proxy/nginx.conf:/etc/nginx/nginx.conf
    # restart: always
    ports:
     - "80:80"

volumes:
  dbdata:
    external: true