version: '3.7'
services:
  web:
    build:
      context: ./components/application/
      dockerfile: ./coderx.Dockerfile
    expose:
     - "5000"
    environment: 
      - FLASK_DEBUG=0
    volumes:
      - "./components/application/CodeRx:/code/CodeRx"
    networks:
      - default

  redis:
    image: "redis:alpine"
    networks:
      - default

  db:
    image: postgres:11.2-alpine
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: CodeRxYourDailyDoseOfCode
      #Password is for development use only, will use docker secrets going forward
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - default

  nginx:
    build:
      context: ./components/
      dockerfile: ./proxy/nginx.Dockerfile
    depends_on:
        - web
    # image: nginx:alpine
    volumes:
      - ./components/proxy/nginx.conf:/etc/nginx/nginx.conf
    # restart: always
    ports:
     - "80:80"
    networks:
      - default

volumes:
  dbdata:
    external: true