"""adding name to problem table

Revision ID: 2c3d3b296ce5
Revises: a119e83a7594
Create Date: 2019-04-29 21:57:40.031230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3d3b296ce5'
down_revision = 'a119e83a7594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'name')
    # ### end Alembic commands ###
