"""empty message

Revision ID: 5414bda76d38
Revises: e1c11f032ce1
Create Date: 2019-04-30 03:55:10.448493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5414bda76d38'
down_revision = 'e1c11f032ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.add_column('problem', sa.Column('name', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('final_submission', sa.Boolean(), nullable=True))
    op.add_column('submission', sa.Column('grade', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('submission', sa.Column('submission_time', sa.DateTime(), nullable=True))
    op.drop_column('submission', 'files')
    op.drop_column('submission', 'new_field')
    op.add_column('user', sa.Column('last_problem_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_problem_id')
    op.add_column('submission', sa.Column('new_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submission', sa.Column('files', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('submission', 'submission_time')
    op.drop_column('submission', 'start_time')
    op.drop_column('submission', 'grade')
    op.drop_column('submission', 'final_submission')
    op.drop_column('problem', 'name')
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name='files_problem_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='files_pkey')
    )
    # ### end Alembic commands ###
